package app.navelo.tv

import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import app.navelo.shared.MediaItem
import coil.compose.AsyncImage
import coil.network.HttpException
import coil.request.ImageRequest
import kotlinx.coroutines.delay
import okhttp3.HttpUrl.Companion.toHttpUrlOrNull

/** Repository access for authenticated, phone-generated artwork requests. */
internal val LocalTvRepository = compositionLocalOf<TvRepository> {
    error("LocalTvRepository was not provided")
}

private enum class ArtworkSource { METADATA, THUMBNAIL, NONE }

private const val MAX_LOCAL_ATTEMPTS = 4
private const val MAX_METADATA_ATTEMPTS = 3

/**
 * Displays phone-cached artwork when it is available and falls back to a frame generated by the phone.
 *
 * Cache keys deliberately exclude the phone's address so artwork survives router/hotspot changes.
 * Only validated relative artwork references can become requests, so the pairing token is never
 * attached to a provider or other remote URL (including URLs in legacy persisted metadata).
 */
@Composable
internal fun NaveloArtwork(
    item: MediaItem,
    artworkReference: String?,
    modifier: Modifier = Modifier,
    contentScale: ContentScale = ContentScale.Crop,
) {
    val repository = LocalTvRepository.current
    val context = LocalContext.current
    val localUrl = repository.thumbnailUrl(item.id)
    val metadataUrl = repository.artworkUrl(artworkReference)
    val artworkId = ArtworkPolicy.assetId(artworkReference)
    val token = repository.authToken()
    val serverId = repository.activeServerId()
    val localCacheKey = remember(serverId, item.id, item.modifiedTime, item.size) {
        "navelo-thumbnail-v1:${serverId.orEmpty()}:${item.id}:${item.modifiedTime}:${item.size}"
    }
    val localRequest = remember(context, localUrl, token, localCacheKey) {
        if (localUrl.isNullOrBlank() || token.isNullOrBlank()) {
            null
        } else {
            ImageRequest.Builder(context)
                .data(localUrl)
                .addHeader("Authorization", "Bearer $token")
                .memoryCacheKey(localCacheKey)
                .diskCacheKey(localCacheKey)
                .build()
        }
    }
    val metadataCacheKey = remember(serverId, artworkId) {
        artworkId?.let { ArtworkPolicy.cacheKey(serverId.orEmpty(), it) }
    }
    val metadataRequest = remember(context, metadataUrl, token, metadataCacheKey) {
        if (metadataUrl.isNullOrBlank() || token.isNullOrBlank() || metadataCacheKey == null) {
            null
        } else {
            ImageRequest.Builder(context)
                .data(metadataUrl)
                .addHeader("Authorization", "Bearer $token")
                .memoryCacheKey(metadataCacheKey)
                .diskCacheKey(metadataCacheKey)
                .build()
        }
    }
    var source by remember(metadataRequest, localUrl, token, localCacheKey) {
        mutableStateOf(
            when {
                metadataRequest != null -> ArtworkSource.METADATA
                localRequest != null -> ArtworkSource.THUMBNAIL
                else -> ArtworkSource.NONE
            }
        )
    }
    var localAttempt by remember(metadataRequest, localUrl, token, localCacheKey) {
        mutableStateOf(0)
    }
    var metadataAttempt by remember(metadataRequest, metadataCacheKey) {
        mutableStateOf(0)
    }
    var pendingRetry by remember(metadataRequest, localUrl, token, localCacheKey) {
        mutableStateOf<Int?>(null)
    }
    var pendingMetadataRetry by remember(metadataRequest, metadataCacheKey) {
        mutableStateOf<Int?>(null)
    }

    // Removing the failed image from composition before the delay guarantees Coil starts a new
    // request even though the stable cache key and URL stay the same. LaunchedEffect is cancelled
    // automatically when this artwork leaves the screen.
    LaunchedEffect(pendingRetry, localCacheKey) {
        val attempt = pendingRetry ?: return@LaunchedEffect
        val jitterMs = item.id.hashCode().toLong() and 0x1ffL
        delay((1_000L shl (attempt - 1).coerceIn(0, 3)) + jitterMs)
        localAttempt = attempt
        pendingRetry = null
        source = ArtworkSource.THUMBNAIL
    }
    LaunchedEffect(pendingMetadataRetry, metadataCacheKey) {
        val attempt = pendingMetadataRetry ?: return@LaunchedEffect
        val jitterMs = item.id.hashCode().toLong() and 0x1ffL
        delay((750L shl (attempt - 1).coerceIn(0, 2)) + jitterMs)
        metadataAttempt = attempt
        pendingMetadataRetry = null
        source = ArtworkSource.METADATA
    }
    val model = when (source) {
        ArtworkSource.METADATA -> metadataRequest
        ArtworkSource.THUMBNAIL -> localRequest
        ArtworkSource.NONE -> null
    }

    if (model != null) {
        AsyncImage(
            model = model,
            contentDescription = null,
            contentScale = contentScale,
            modifier = modifier,
            onError = { error ->
                if (BuildConfig.DEBUG) android.util.Log.d("NaveloArtwork", "Artwork failed: ${error.result.throwable}")
                when {
                    source == ArtworkSource.METADATA &&
                        error.result.throwable.isTemporaryArtworkFailure() &&
                        metadataAttempt + 1 < MAX_METADATA_ATTEMPTS -> {
                        source = ArtworkSource.NONE
                        pendingMetadataRetry = metadataAttempt + 1
                    }
                    source == ArtworkSource.METADATA && localRequest != null -> {
                        source = ArtworkSource.THUMBNAIL
                    }
                    source == ArtworkSource.THUMBNAIL &&
                        error.result.throwable.isTemporaryArtworkFailure() &&
                        localAttempt + 1 < MAX_LOCAL_ATTEMPTS -> {
                        source = ArtworkSource.NONE
                        pendingRetry = localAttempt + 1
                    }
                    else -> {
                        source = ArtworkSource.NONE
                        pendingRetry = null
                    }
                }
            },
        )
    }
}

/** Strictly maps phone-issued relative artwork references back to that same phone. */
internal object ArtworkPolicy {
    private const val PREFIX = "/api/v1/artwork/"
    private val OPAQUE_ID = Regex("[A-Za-z0-9_-]{1,256}")

    fun assetId(reference: String?): String? {
        val value = reference?.trim()?.takeIf { it.startsWith(PREFIX) } ?: return null
        return value.removePrefix(PREFIX).takeIf { OPAQUE_ID.matches(it) }
    }

    fun artworkUrl(server: app.navelo.shared.DiscoveredServer, reference: String?): String? {
        val id = assetId(reference) ?: return null
        return server.baseUrl.toHttpUrlOrNull()?.newBuilder()
            ?.addPathSegments("api/v1/artwork")
            ?.addPathSegment(id)
            ?.build()
            ?.toString()
    }

    fun cacheKey(serverId: String, artworkId: String): String =
        "navelo-artwork-v1:$serverId:$artworkId"
}

private fun Throwable.isTemporaryArtworkFailure(): Boolean =
    generateSequence(this) { it.cause }
        .filterIsInstance<HttpException>()
        .firstOrNull()
        ?.response
        ?.code
        .let { it == 429 || it == 503 }
